@startuml
class trabalho1.Agencia {
- int codigo
- String nome
- String endereco
- ArrayList<Conta> contas
+ int getCodigo()
+ void setCodigo(int)
+ String getNome()
+ void setNome(String)
+ String getEndereco()
+ void setEndereco(String)
+ ArrayList<Conta> getContas()
+ void cadastrarConta(Conta)
+ Conta buscarConta(int,String)
+ Conta buscarConta(int)
}
class trabalho1.Conta {
- int numero
- int agencia
- double saldo
- String nome
- String endereco
- String cpf
- String dataNascimento
- String senha
- ArrayList<String> extrato
+ int getNumero()
+ void setNumero(int)
+ double getSaldo()
+ int getAgencia()
+ void setAgencia(int)
+ void setSaldo(double)
+ String getNome()
+ void setNome(String)
+ String getEndereco()
+ void setEndereco(String)
+ String getCpf()
+ void setCpf(String)
+ String getDataNascimento()
+ void setDataNascimento(String)
+ String getSenha()
+ ArrayList<String> getExtrato()
+ void setExtrato(ArrayList<String>)
+ void depositar(double)
+ void sacar(double)
+ boolean validarSenha(String)
+ boolean setSenha(String,String)
+ void novaOperacao(String,double)
+ void novaOperacao(String,double,String)
}
class trabalho1.DisplayBanco {
- Banco meuBanco
+ void login()
+ void telaUsuario()
- void operacaoDeposito()
- void operacaoSaque()
- void operacaoPix()
- void operacaoTransferencia()
- void operacaoSaldo()
- void operacaoExtrato()
- void alterarSenha()
- void operacaoSair()
}
class trabalho1.Banco {
- String nome
- String cnpj
- String endereco
- Conta contaLogada
- ArrayList<Agencia> agencias
+ String getNome()
+ void setNome(String)
+ String getCnpj()
+ void setCnpj(String)
+ String getEndereco()
+ void setEndereco(String)
+ Conta getContaLogada()
+ void setContaLogada(Conta)
+ ArrayList<Agencia> getAgencias()
+ void setAgencias(ArrayList<Agencia>)
+ void logarCliente(int,int,String)
+ boolean realizarSaque(double)
+ void realizarDeposito(double)
+ double saldo()
+ ArrayList<String> extrato()
+ void cadastrarAgencia(String,int,String)
+ void cadastrarAgencia(Agencia)
+ void cadastrarConta(int,int,String,double,String,String,String,String)
+ Agencia buscarAgencia(int)
+ boolean transferencia(int,int,float)
+ boolean pix(String,float)
+ void deslogarConta()
}
class trabalho1.Main {
+ {static} void main(String[])
}
@enduml